# Linear Systems : Matrices, Vectors, eigen systems
In this module we will learn how to solve linear systems which are very common in engineering.
Applications are numerous: 
- Civil, chemical, electrical, mechanical, ..., engineering
- In biology by using linear algebra to analyze huge data sets regarding protein folding. https://math.stackexchange.com/questions/571109/any-application-of-vector-spaces-in-biology-or-biotechnology
- In genetics to model the evolution of genes.
- Markov chains on industrial processes with applications of matrices and eigen systems. 
- Population dynamics. 
- Perception of colors. 

<img src="fig/Linear-Systems-Applications.png" width=900>

<img src="fig/Matrices-rotations-eigenvalues.png" width=900>


Ejemplos de rotaciones:
- https://www.glowscript.org/#/user/GlowScriptDemos/folder/Examples/program/Bounce-VPython
- https://www.glowscript.org/#/user/GlowScriptDemos/folder/Examples/program/Plot3D

<img src="fig/bungee-family-equ.png" width=900>

> Write this as a linear system $A\vec x = \vec b$, with unknows $x_1, x_2, x_3$



A = (k1+k2  -k2      0 
     -k2    k2+k3   -k3 
     0      -k3      k3) 
     
    [[k1 + k2, -k2  , 0  ],
     [-k2    , k2+k3, -k3],
     [0      , -k3  , k3]]

x = (x1
     x2
     x3)
     
b = (m1g
     m2g
     m3g)

# How to index a Matrix?
<img src="fig/matrix-base.png" width=900>

# Defining matrices in python

## Scipy
See https://docs.scipy.org/doc/numpy-1.17.0/reference/generated/numpy.array.html#numpy.array



In [19]:
import numpy as np
A = np.array([[1, 2],  # primera fila, indice es 0
              [3, 4]]) # Segunda fila, indice es 1
print(A[0][1])
print(f"Matrix : \n", A)
#
A = np.array([1, 2, 3, 4]).reshape(2,2)
print("Matrix : \n", A)
print("A[1,0] : \n", A[1,0])
print("A[1][0] : \n", A[1][0])

2
Matrix : 
 [[1 2]
 [3 4]]
Matrix : 
 [[1 2]
 [3 4]]
A[1,0] : 
 3
A[1][0] : 
 3


## Sympy
See https://docs.sympy.org/latest/modules/matrices/matrices.html

In [1]:
from sympy.matrices import Matrix, eye, zeros, ones, diag
M = Matrix([[1,0,4], [0,0,0]])
print(M)
print(eye(4))
print(M[0, 2])

Matrix([[1, 0, 4], [0, 0, 0]])
Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
4


# Matrix operations
Add, substract, multiply, etc


In [22]:
import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, -1], [-3, 24]])
c = a+b # sum
print(c)
c = a*b # Multiplication
print(c)
c = a/b # divide element by element
print(c)
print(c.max())
print(c.min())
print(b/b)

[[ 6  1]
 [ 0 28]]
[[ 5 -2]
 [-9 96]]
[[ 0.2        -2.        ]
 [-1.          0.16666667]]
0.2
-2.0
[[1. 1.]
 [1. 1.]]


# Solving linear systems $A\vec x= \vec b$
Solve the following system:
<img src="fig/linear-example-01.png" width=600>

In [26]:
import numpy as np

A = np.array([[150, -100, 0], 
              [-100, 150, -50], 
              [0, -50, 50]])
b = np.array([588.6, 686.7, 784.8])
x = np.linalg.solve(A, b) # magic
print("Solution: \n", x)
# confirm
print("Delta:\n", A.dot(x) - b)

Solution: 
 [41.202 55.917 71.613]
Delta:
 [-5.68434189e-13  1.13686838e-12  2.27373675e-13]
Delta:
 [[ 5591.7  -6278.4   -784.8 ]
 [-4708.8   7700.85 -4365.45]
 [ -588.6  -3482.55  2795.85]]


In [32]:
import numpy as np

N = 1000

A = np.random.rand(N,N)
b = np.random.rand(N)
x = np.linalg.solve(A, b) # magic
#print("Solution: \n", x)
# confirm
#print("Delta:\n", A.dot(x) - b)

## Exercise: Rewrite and solve the following system

<img src="fig/linear-example-03.png" width=600>

## Exercise: Rewrite and solve the following system
Extra: Can yu measure the time spent in the computation? (google for timer or timeit in python)

<img src="fig/linear-example-02.png" width=600>

## Exercise: Solve and plot the following system

$$ \frac{-2.3x_1}{5} + x_2 = 1.1 $$
$$-0.5x_1 + x_2 = 1 $$
Plot the system of equations and check whether this solution is or
not special.


## Exercise: Simulating temperature
|Temperature| System of equations|
|-|-|
|<img src="fig/linear-example-04-T.png" width=800>| <img src="fig/linear-example-04-T-B.png" width=800>|

# Computing inverse matrices
See : https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.inv.html#scipy.linalg.inv

You can watch: https://www.youtube.com/watch?v=uQhTuRlWMxw



In [39]:
%time
from scipy import linalg
import numpy as np
A = np.array([[1., 2.], 
              [3., 4.]])
B = linalg.inv(A) # magic
print("B : \n", B)
# verify
print("A A^-1 : \n", A.dot(B))

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 7.15 µs
B : 
 [[-2.   1. ]
 [ 1.5 -0.5]]
A A^-1 : 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [54]:
from scipy import linalg
import numpy as np
N = 100
A = np.random.rand(N, N)
B = linalg.inv(A) # magic
print("B : \n", B)
# verify
print("A A^-1 : \n", A.dot(B))

B : 
 [[ 0.44756723 -1.14521877  1.42804181 ... -1.56132941  0.10250601
  -1.98266296]
 [-0.10567368 -0.96711226  1.39052346 ... -1.24106902 -0.01001206
  -1.52696587]
 [ 1.14646293  0.6486871   0.26726554 ... -0.69599977 -0.45806245
  -1.00361999]
 ...
 [-0.07606704 -0.11952533  0.17765931 ... -0.13975646 -0.14627226
  -0.12783145]
 [ 0.10417006 -0.11689156  0.3151257  ...  0.30797543  0.61456587
  -0.22365001]
 [ 0.4168966  -1.5252574   2.38868665 ... -2.19771986  0.53393421
  -3.05294665]]
A A^-1 : 
 [[ 1.00000000e+00  1.12715290e-14 -6.37682776e-14 ...  8.95667191e-16
   1.63261600e-15  1.32194344e-14]
 [-1.30692001e-14  1.00000000e+00 -2.16945628e-15 ...  1.44342564e-14
  -2.14333676e-15 -1.24136401e-14]
 [-1.16989664e-14  9.41447482e-15  1.00000000e+00 ...  1.26981790e-14
   4.43242372e-16  7.15432717e-15]
 ...
 [-1.30286573e-14  1.33518689e-14 -4.82681630e-14 ...  1.00000000e+00
   5.51615469e-15  8.13355162e-16]
 [-1.08702008e-14  9.45616874e-15 -4.18010371e-14 ...  8.04889861e

## The condition number
The number
$$\kappa = ||A|| ||A^{-1}||$$
is called the condition number of a matrix. Ideally it is $1$. If $\kappa$ is much
larger than one, the matrix is ill-conditioned and the solution
might have a lot of error.
> Compute the condition number of the following matrix:
   \begin{equation}
   A = 
   \begin{bmatrix}
   1.001 & 0.001\\
   0.000 & 0.999
   \end{bmatrix}
   \end{equation}
Plot the associate system to check for the result


In [55]:
from scipy import linalg
import numpy as np
A = np.array([[1.001, 0.001],
                [0.000, 0.999]])
kappa = linalg.norm(A)*linalg.norm(linalg.inv(A))
print(f"{kappa = }")

kappa = 2.000005000005


# Eigen values and eigen vectors
The eigen-values ${\lambda_i}$ and eigen-vectors ${x}$ of a matrix satisfy the equation 

$$ A\vec x = \lambda \vec x $$

The eigen-vectors form a basis where the matrix can be
diagonalized. In general, computing the eigen vectors and
aeigenvalues is hard, and they can also be complex.

For a more visual introduction watch:  https://www.youtube.com/watch?v=PFDu9oVAE-g

<img src="fig/vector-field.png" width=700>
REF: https://www.reddit.com/r/math/comments/b7ou6t/3blue1brown_overview_of_differential_equations/

In [60]:
# See : https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eig.html#scipy.linalg.eig
import numpy as np
from scipy import linalg
#A = np.array([[0., -1.], [1., 0.]])
#A = np.array([[1, 0.], [0., 2.]])
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
sol = linalg.eig(A) # magic
print("Eigen-values: ", sol[0])
print("Eigen-vectors:\n", sol[1])
# verify
print("Verification: ", A.dot(sol[1][:, 0]) - sol[0][0]*sol[1][:, 0])


Eigen-values:  [21.16354031+0.j -4.30600676+0.j -0.99565101+0.j  2.13811747+0.j]
Eigen-vectors:
 [[ 0.52214026  0.8395     -0.13395285  0.33729784]
 [ 0.40138661 -0.44433929  0.90363128 -0.52754624]
 [ 0.56847945 -0.29618232 -0.37349291  0.67580022]
 [ 0.49304103 -0.1003911  -0.16127674 -0.38886912]]
Verification:  [5.32907052e-15+0.j 1.59872116e-14+0.j 1.59872116e-14+0.j
 1.06581410e-14+0.j]


## Exercise
Find the eigen-values and eigen-vectors for the following system
<img src="fig/eigen-exer-02.png" width=700>

In [66]:
import numpy as np
from scipy import linalg
A = np.array([[5, 4, 1, 1], 
              [4, 5, 1, 1], 
              [1, 1, 4, 2], 
              [1, 1, 2, 4]])
sol = linalg.eig(A) # magic
print("Eigen-values: ", sol[0])
print("Eigen-vectors:\n", sol[1])
# verify
print("Verification: ", A.dot(sol[1][:, 0]) - sol[0][0]*sol[1][:, 0])


Eigen-values:  [10.+0.j  1.+0.j  5.+0.j  2.+0.j]
Eigen-vectors:
 [[-6.32455532e-01 -7.07106781e-01  3.16227766e-01  1.66533454e-16]
 [-6.32455532e-01  7.07106781e-01  3.16227766e-01 -5.55111512e-17]
 [-3.16227766e-01 -5.81000260e-17 -6.32455532e-01 -7.07106781e-01]
 [-3.16227766e-01 -8.58556016e-17 -6.32455532e-01  7.07106781e-01]]
Verification:  [-8.88178420e-16+0.j -4.44089210e-15+0.j -1.77635684e-15+0.j
 -2.22044605e-15+0.j]


# Problems

<img src="fig/problem-03.png" width=700>

Let $\vec x = (a, b)$ be a two-dimensional vector. Write a matrix that rotates the vector by 90 degrees. Use matrix multiplication to check your results. 

|System | Model |
|-|-|
|<img src="fig/problem-04-B.png" width=700>|<img src="fig/problem-04.png" width=700>|

In [69]:
# Equations
# Q01c01 + Q31c3 = Q15c1 + Q12c1 ---> (Q15 + Q12)c1 - Q31c3           = Q01c01
# Q12c1 = Q25c2 + Q24c2 + Q23c2  ---> Q12c1 - (Q25 + Q24 + Q23) c2    = 0
# Q23c2 + Q03c03 = Q31c3 + Q34c3 ---> Q23c2 - (Q31 + Q34)c3           = -Q03c03
# Q24c2 + Q34c3 + Q54c5 = Q44c4  ---> Q24c2 + Q34c3 - Q44c4 + Q54c5 = 0
# Q15c1 + Q25c2 = Q54c5 + Q55c5  ---> Q15c1 + Q25c2 - (Q54 + Q55)c5   = 0

Q01 = 6; Q03 = 7
Q12 = 4; Q15 = 5
Q23 = 2; Q24 = 1; Q25 = 1
Q31 = 3; Q34 = 6
Q44 = 9
Q54 = 2; Q55 = 4
c01 = 20; c03 = 50

from scipy import linalg
import numpy as np
A = np.array([[(Q15 + Q12), 0, - Q31, 0, 0],
              [Q12, -(Q25 + Q24 + Q23), 0, 0, 0],
              [0, Q23, -(Q31 + Q34), 0, 0],
              [0, Q24, Q34, - Q44, Q54],
              [Q15, Q25, 0, 0, -(Q54 + Q55)]])
b = np.array([Q01*c01, 0, -Q03*c03, 0, 0])
c = linalg.solve(A, b)
print(c)
# Check
print(A.dot(c) - b)

[28.4 28.4 45.2 39.6 28.4]
[ 0.00000000e+00  0.00000000e+00  5.68434189e-14 -7.10542736e-15
  0.00000000e+00]


<img src="fig/problem-05.png" width=700>

<img src="fig/problem-06.png" width=700>

| Statement | Table|
|-|-|
|<img src="fig/problem-07-A.png" width=500> | <img src="fig/problem-07-B.png" width=500>|

<img src="fig/problem-08.png" width=700>