# Linear Systems : Matrices, Vectors, eigen systems
In this module we will learn how to solve linear systems which are very common in engineering.
Applications are numerous: 
- Civil, chemical, electrical, mechanical, ..., engineering
- In biology by using linear algebra to analyze huge data sets regarding protein folding. https://math.stackexchange.com/questions/571109/any-application-of-vector-spaces-in-biology-or-biotechnology
- In genetics to model the evolution of genes.
- Markov chains on industrial processes with applications of matrices and eigen systems. 
- Population dynamics. 
- Perception of colors. 

<img src="fig/Linear-Systems-Applications.png" width=900>

<img src="fig/Matrices-rotations-eigenvalues.png" width=900>


Ejemplos de rotaciones:
- https://www.glowscript.org/#/user/GlowScriptDemos/folder/Examples/program/Bounce-VPython
- https://www.glowscript.org/#/user/GlowScriptDemos/folder/Examples/program/Plot3D

<img src="fig/bungee-family-equ.png" width=900>

> Write this as a linear system $A\vec x = \vec b$, with unknows $x_1, x_2, x_3$

# How to index a Matrix?
<img src="fig/matrix-base.png" width=900>

# Defining matrices in python

## Scipy
See https://docs.scipy.org/doc/numpy-1.17.0/reference/generated/numpy.array.html#numpy.array



In [11]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print("Matrix : \n", a)
a = np.array([1, 2, 3, 4]).reshape(2,2)
print("Matrix : \n", a)
print("a[1,0] : \n", a[1,0])

Matrix : 
 [[1 2]
 [3 4]]
Matrix : 
 [[1 2]
 [3 4]]
a[1,0] : 
 3


## Sympy
See https://docs.sympy.org/latest/modules/matrices/matrices.html

In [1]:
from sympy.matrices import Matrix, eye, zeros, ones, diag
M = Matrix([[1,0,4], [0,0,0]])
print(M)
print(eye(4))
print(M[0, 2])

Matrix([[1, 0, 4], [0, 0, 0]])
Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
4


# Matrix operations
Add, substract, multiply, etc


In [15]:
import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, -1], [-3, 24]])
c = a+b # sum
print(c)
c = a*b # Multiplication
print(c)
c = a/b # multiply by the inverse of b
print(c)
print(c.max())
print(c.min())

[[ 6  1]
 [ 0 28]]
[[ 5 -2]
 [-9 96]]
[[ 0.2        -2.        ]
 [-1.          0.16666667]]
0.2
-2.0


# Solving linear systems $A\vec x= \vec b$
Solve the following system:
<img src="fig/linear-example-01.png" width=600>

In [20]:
import numpy as np

A = np.array([[150, -100, 0], [-100, 150, -50], [0, -50, 50]])
b = np.array([588.6, 686.7, 784.8])
x = np.linalg.solve(A, b) # magic
print("Solution: \n", x)
# confirm
print("Delta:\n", A.dot(x) - b)

Solution: 
 [41.202 55.917 71.613]
Delta:
 [-5.68434189e-13 -2.27373675e-13  2.27373675e-13]


## Exercise: Rewrite and solve the following system

<img src="fig/linear-example-03.png" width=600>

## Exercise: Rewrite and solve the following system
Extra: Can yu measure the time spent in the computation? (google for timer or timeit in python)

<img src="fig/linear-example-02.png" width=600>

## Exercise: Solve and plot the following system

$$ \frac{-2.3x_1}{5} + x_2 = 1.1 $$
$$-0.5x_1 + x_2 = 1 $$
Plot the system of equations and check whether this solution is or
not special.


## Exercise: Simulating temperature
|Temperature| System of equations|
|-|-|
|<img src="fig/linear-example-04-T.png" width=800>| <img src="fig/linear-example-04-T-B.png" width=800>|

# Computing inverse matrices
See : https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.inv.html#scipy.linalg.inv

You can watch: https://www.youtube.com/watch?v=uQhTuRlWMxw



In [23]:
from scipy import linalg
import numpy as np
A = np.array([[1., 2.], [3., 4.]])
B = linalg.inv(A) # magic
print("B : \n", B)
# verify
print("B B^-1 : \n", A.dot(B))

B : 
 [[-2.   1. ]
 [ 1.5 -0.5]]
B B^-1 : 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## The condition number
The number
$$\kappa = ||A|| ||A^{-1}||$$
is called the condition number of a matrix. Ideally it is $1$. If $\kappa$ is much
larger than one, the matrix is ill-conditioned and the solution
might have a lot of error.
> Compute the condition number of the following matrix:
   \begin{equation}
   A = 
   \begin{bmatrix}
   1.001 & 0.001\\
   0.000 & 0.999
   \end{bmatrix}
   \end{equation}
Plot the associate system to check for the result


# Eigen values and eigen vectors
The eigen-values ${\lambda_i}$ and eigen-vectors ${x}$ of a matrix satisfy the equation 

$$ A\vec x = \lambda \vec x $$

The eigen-vectors form a basis where the matrix can be
diagonalized. In general, computing the eigen vectors and
aeigenvalues is hard, and they can also be complex.

For a more visual introduction watch:  https://www.youtube.com/watch?v=PFDu9oVAE-g

<img src="fig/vector-field.png" width=700>
REF: https://www.reddit.com/r/math/comments/b7ou6t/3blue1brown_overview_of_differential_equations/

In [25]:
# See : https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eig.html#scipy.linalg.eig
import numpy as np
from scipy import linalg
A = np.array([[0., -1.], [1., 0.]])
#A = np.array([[1, 0.], [0., 2.]])
#A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
#A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
sol = linalg.eig(A) # magic
print("Eigen-values: ", sol[0])
print("Eigen-vectors:\n", sol[1])
# verify
print("Verification: ", A.dot(sol[1][:, 0]) - sol[0][0]*sol[1][:, 0])


Eigen-values:  [0.+1.j 0.-1.j]
Eigen-vectors:
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]
Verification:  [0.+0.j 0.+0.j]


## Exercise
Find the eigen-values and eigen-vectors for the following system
<img src="fig/eigen-exer-02.png" width=700>

# Problems

<img src="fig/problem-03.png" width=700>

Let $\vec x = (a, b)$ be a two-dimensional vector. Write a matrix that rotates the vector by 90 degrees. Use matrix multiplication to check your results. 

|System | Model |
|-|-|
|<img src="fig/problem-04-B.png" width=700>|<img src="fig/problem-04.png" width=700>|

<img src="fig/problem-05.png" width=700>

<img src="fig/problem-06.png" width=700>

| Statement | Table|
|-|-|
|<img src="fig/problem-07-A.png" width=500> | <img src="fig/problem-07-B.png" width=500>|

<img src="fig/problem-08.png" width=700>